[package]
name = "feedback_visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
feedback_core = { path = "../feedback_core" }
feedback_analysis = { path = "../feedback_analysis" }
plotters = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }