[package]
name = "feedback_visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
feedback_core = { path = "../feedback_core" }
feedback_analysis = { path = "../feedback_analysis" }
plotters = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }