[package]
name = "skill_volunteering"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "skill_volunteering_server"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
rust_decimal = { workspace = true }

# External dependencies for gRPC
# The cause_management service will be a client
cause_management = { path = "../cause_management" }

[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }