[package]
name = "pds"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.6", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
mime_guess = "2.0"
once_cell = "1.19.0"
lazy_static = "1.4.0"
crossbeam-channel = "0.5.12"
jni = { version = "0.21.1", features = ["default"] }
log = "0.4"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
cpc-core = { path = "../../../packages/cpc-core" }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
thiserror = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "migrate"] }
argon2 = { version = "0.5", features = ["std"] }
dotenv = "0.15"
regex = "1.10"  // For input validation
graphql_client = "0.13.0"
reqwest = { version = "0.11", features = ["json"] }
yew-hooks = "0.3.1"

# Plotting
plotters = "0.3.5"
plotters-canvas = "0.3.5"
plotters-svg = "0.3.5"
plotters-yew = { version = "0.3.5", default-features = false }

# Yew dependencies
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"
yewdux = "0.9"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
url = "2.5.0"
gloo-net = { version = "0.5.0", features = ["http"] }
gloo-console = "0.3.0"
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"