[package]
name = "pds"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.6", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
mime_guess = "2.0"
once_cell = "1.19.0"
lazy_static = "1.4.0"
crossbeam-channel = "0.5.12"
jni = { version = "0.21.1", features = ["default"] }
log = "0.4"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
cpc-core = { path = "../../../packages/cpc-core" }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
thiserror = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "migrate"] }
argon2 = { version = "0.5", features = ["std"] }
dotenv = "0.15"
regex = "1.10"  // For input validation

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"