[package]
name = "cpc_statistics_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
statrs = { workspace = true }
polars = { workspace = true }
ndarray = { workspace = true }
ndarray-stats = { workspace = true }
thiserror = { workspace = true }