[package]
name = "cpc-android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# JNI bindings
jni = "0.21"

# Async runtime
tokio = { workspace = true, features = ["full"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bincode = "1.3"

# UUID handling
uuid = { workspace = true, features = ["v4", "serde"] }

# Database
sled = { workspace = true }

# CPC domain dependencies
packages.domains.sheets = { path = "../../../packages/domains/sheets" }
packages.domains.finance = { path = "../../../packages/domains/finance" }

# CPC infra dependencies
packages.infra = { path = "../../../packages/infra" }

# For testing
tempfile = "3.0"