[package]
name = "storage_abstraction"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Storage backends
sled = "0.34"
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "sqlite"] }

# Optional dependencies
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }