[package]
name = "learning_platform_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
config = "0.14"
dotenv = "0.15"
jsonwebtoken = { workspace = true }
bcrypt = "0.15"
thiserror = { workspace = true }

# Shared core library
learning_core = { path = "../../shared_packages/learning_core" }

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }

[[example]]
name = "client"
path = "examples/client.rs"

[lib]
name = "learning_platform_server"
path = "src/lib.rs"

[[bin]]
name = "learning_platform_server"
path = "src/main.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"

[[bench]]
name = "service_benchmark"
harness = false

[[bench]]
name = "utils_benchmark"
harness = false