[package]
name = "shtairir_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
redis = { workspace = true }
bb8 = { workspace = true }
bb8-redis = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
regex = { version = "1.5", default-features = false }

[[example]]
name = "example_app"
path = "examples/example_app.rs"