[package]
name = "feedback_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
reviews = { path = "../reviews" }
survey = { path = "../survey" }
uuid = { version = "1.0", features = ["v4", "serde"] }