[package]
name = "feedback_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reviews = { path = "../reviews" }
survey = { path = "../survey" }
uuid = { workspace = true, features = ["v4", "serde"] }