[package]
name = "messenger_infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }

# Async support
async-trait = { workspace = true }

# Domain and application layers
messenger_domain = { path = "../../domains/messenger" }
messenger_app = { path = "../../apps/messenger" }

# Core services
consent_manager = { path = "../../core/consent_manager" }
event_bus = { path = "../../core/event_bus" }
storage_abstraction = { path = "../../core/storage_abstraction" }
notification_core = { path = "../../core/notification_core" }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }

# Web framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# GraphQL
async-graphql = "7.0"
async-graphql-axum = "7.0"

# WebSocket support
tokio-tungstenite = "0.20"

# OAuth2 for authentication
oauth2 = "4.4"

# Sled for local caching
sled = "0.34"

# Encryption
rust-crypto = "0.2"