[package]
name = "skill_tracking"
version = "0.1.0"
edition = "2021"
authors = ["CPC Cooperative <cooperative@cpc.dev>"]

[dependencies]
# Tauri
tauri = { workspace = true, features = ["shell-open"] }
tauri-plugin-shell = "2.0.0-rc"

# Yew
yew = { workspace = true, features = ["csr"] }
stylist = { workspace = true }

# CPC Dependencies
skill_development = { path = "../../shared_packages/skill_development" }
skill_volunteering = { path = "../../shared_packages/skill_volunteering" }
social_integration = { path = "../../shared_packages/social_integration" }

# Async
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
gloo = "0.8"

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# gRPC
tonic = { workspace = true, features = ["prost", "codegen"] }
prost = { workspace = true }

# UUID
uuid = { workspace = true, features = ["v4", "serde", "js"] }

# Time
chrono = { workspace = true, features = ["serde"] }

# Plotting
plotters = { workspace = true, features = ["wasm-backend"] }

# HTTP Client
reqwest = { version = "0.12", features = ["json", "wasm-bindgen"] }

# Logging
wasm-logger = { workspace = true }
log = { workspace = true }

[build-dependencies]
tonic-build = "0.12"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "skill_tracking_lib"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "skill_tracking"
path = "src/main.rs"