[package]
name = "cpc-studio"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.4", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
uuid = { version = "1.3", features = ["v4", "serde"] }
bevy = { version = "0.13", features = ["dynamic"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "net"] }
futures = "0.3"
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
cpc-core = { path = "../../../packages/cpc-core" }