[package]
name = "cpc-studio"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.4", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bevy = "0.9"
image = "0.24.6"
base64 = "0.21.5"