export function getFileIcon(filename) {
  const ext = filename.split('.').pop().toLowerCase();
  const icons = {
    jpg: '🖼️',
    jpeg: '🖼️',
    png: '🖼️',
    gif: '🖼️',
    bmp: '🖼️',
    svg: '🖼️',
    webp: '🖼️',
    mp3: '🔊',
    wav: '🔊',
    ogg: '🔊',
    mp4: '🎬',
    mov: '🎬',
    avi: '🎬',
    pdf: '📄',
    doc: '📝',
    docx: '📝',
    xls: '📊',
    xlsx: '📊',
    ppt: '📑',
    pptx: '📑',
    txt: '📝',
    md: '📝',
    js: '📜',
    jsx: '📜',
    ts: '📜',
    tsx: '📜',
    json: '📄',
    html: '🌐',
    htm: '🌐',
    css: '🎨',
    scss: '🎨',
    zip: '📦',
    rar: '📦',
    '7z': '📦',
    tar: '📦',
    gz: '📦',
    exe: '⚙️',
    dll: '⚙️',
    sh: '💻',
    bat: '💻',
    ps1: '💻',
    py: '🐍',
    java: '☕',
    class: '☕',
    jar: '☕',
    cs: '⚙️',
    go: '🐹',
    php: '🐘',
    rb: '💎',
    rs: '🦀'
  };
  return icons[ext] || '📄';
}

export function getFileCategory(filename) {
  const ext = filename.split('.').pop().toLowerCase();
  const categories = {
    jpg: 'images',
    jpeg: 'images',
    png: 'images',
    gif: 'images',
    bmp: 'images',
    svg: 'images',
    webp: 'images',
    mp3: 'audio',
    wav: 'audio',
    ogg: 'audio',
    mp4: 'video',
    mov: 'video',
    avi: 'video',
    pdf: 'documents',
    doc: 'documents',
    docx: 'documents',
    xls: 'documents',
    xlsx: 'documents',
    ppt: 'documents',
    pptx: 'documents',
    txt: 'documents',
    md: 'documents',
    js: 'code',
    jsx: 'code',
    ts: 'code',
    tsx: 'code',
    json: 'code',
    html: 'code',
    htm: 'code',
    css: 'code',
    scss: 'code',
    zip: 'archives',
    rar: 'archives',
    '7z': 'archives',
    tar: 'archives',
    gz: 'archives',
    exe: 'executables',
    dll: 'executables',
    sh: 'scripts',
    bat: 'scripts',
    ps1: 'scripts',
    py: 'scripts',
    java: 'code',
    class: 'code',
    jar: 'code',
    cs: 'code',
    go: 'code',
    php: 'code',
    rb: 'code',
    rs: 'code'
  };
  return categories[ext] || 'other';
}