[package]
name = "cpc-node"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cpc-lib = { path = "../lib" }
tokio = { version = "1.0", features = ["full"] }
rusqlite = "0.29"
rocksdb = "0.21.0"
rust-libp2p-metrics = "0.16.0"