[package]
name = "cooperative_fundraising"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

# CPC ecosystem dependencies
wallet = { path = "../wallet" }
cpay_core = { path = "../cpay_core" }
skill_volunteering = { path = "../skill_volunteering" }

# gRPC dependencies
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }