[package]
name = "cause_management"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cause_management"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
statrs = { workspace = true }

# Local dependencies
cpc_statistics_core = { path = "../cpc_statistics_core", optional = true }
polars = { version = "0.35.0", optional = true }
linfa = { version = "0.7.0", optional = true }
bi_visualization = { path = "../bi_visualization", optional = true }
ml_core = { path = "../ml_core" }

[build-dependencies]
tonic-build = "0.14.0"

[features]
default = []
statistics = ["cpc_statistics_core", "polars", "linfa"]
visualization = ["bi_visualization"]