[package]
name = "cpc-messenger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "messenger"
path = "src/main.rs"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Domain layer
messenger_domain = { path = "../../packages/domains/messenger" }

# Application layer
messenger_app = { path = "../../packages/apps/messenger" }

# Infrastructure layer
messenger_infrastructure = { path = "../../packages/infrastructure/messenger" }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }

# Web framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# GraphQL
async-graphql = "7.0"
async-graphql-axum = "7.0"

# WebSocket support
tokio-tungstenite = "0.20"

# OAuth2 for authentication
oauth2 = "4.4"

# Sled for local caching
sled = "0.34"

# Encryption
rust-crypto = "0.2"

# Consent manager
consent_manager = { path = "../../packages/core/consent_manager" }

[dev-dependencies]
tempfile = "3.8"