[package]
name = "feed_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Social graph for content items
social_graph = { path = "../social_graph" }

# Collaborative docs for document previews
collaborative_docs = { path = "../collaborative_docs" }

# Time handling
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"