
[package]
name = "cpc_wallet"
version = "0.2.0"
edition = "2021"

[dependencies]
# Async traits
async-trait = { workspace = true }

# GraphQL
async-graphql = { workspace = true }
async-stream = { workspace = true }
tokio-stream = "0.1.14"
futures-util = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }

# UUID for identifiers
uuid = { workspace = true, features = ["v4", "serde"] }

# Time handling
chrono = { workspace = true, features = ["serde"] }

# Decimal numbers for financial calculations
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

# Logging
tracing = { workspace = true }

# Common utilities
common_utils = { path = "../common_utils" }

[features]
default = ["common-utils-integration"]
common-utils-integration = []

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-test = "0.4"