[package]
name = "skill_profile_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true, features = ["csr"] }
stylist = { workspace = true, features = ["yew_integration"] }
gloo = "0.11.0"
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6"

# gRPC dependencies
tonic = { workspace = true, features = ["prost"] }
prost = { workspace = true }
tonic-web-wasm-client = "0.4.0"
wasm-bindgen-futures = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }


[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }