[package]
name = "skill_profile_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
stylist = { version = "0.13.0", features = ["yew_integration"] }
gloo = "0.11.0"
wasm-bindgen = "0.2"
web-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"

# gRPC dependencies
tonic = { version = "0.11", features = ["prost"] }
prost = "0.12"
tonic-web-wasm-client = "0.4.0"
wasm-bindgen-futures = "0.4"
getrandom = { version = "0.2", features = ["js"] }


[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }