# Concatenate strings with an optional separator
id = "stdlib.shtairir/string.concat@0.1.0"
namespace = "stdlib.shtairir"
name = "string.concat"
version = "0.1.0"
title = "Concat"
description = "Concatenates multiple strings with an optional separator. Supports both simple and pattern-based operations. Unicode-aware implementation."
authors = ["CPC Coop"]
license = "CPC"
tags = ["string", "pure", "concatenation"]
purity = "pure"
effects = []
determinism = "Deterministic"

# Inputs: strings to concatenate
inputs = [
  { name = "strings", ty = "list<string>" },
  { name = "separator", ty = "option<string>", default = null }
]

# No params for this block
params = []

# Output: concatenated string
outputs = [
  { name = "result", ty = "string" }
]

examples = [
  "result = string.concat(strings:[\"hello\", \"world\"])  # → \"helloworld\"",
  "result = string.concat(strings:[\"hello\", \"world\"], separator:\" \")  # → \"hello world\""
]

[engine]
version_req = "^0.2"
capability_flags = ["serde", "pure_values"]

[integrity]
content_hash = "sha256:REPLACEME"