[workspace]
resolver = "2"
members = [
    "data_processing",
    "user_profiles",
    "ml_features",
]

[workspace.dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
shtairir_core = { path = "../../../shared_packages/shtairir_core" }
shtairir_registry = { path = "../../../shared_packages/shtairir_registry" }
shtairir_execution = { path = "../../../shared_packages/shtairir_execution" }
shtairir_blocks = { path = "../../../shared_packages/shtairir_blocks" }