[package]
name = "cpc-website-builder"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
tracing = "0.1"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Async
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# GraphQL
async-graphql = "7.0"

# CPC dependencies
cpc-core = { path = "../../packages/cpc-core" }
cpc-net = { path = "../../packages/cpc-net" }
cpc-protos = { path = "../../packages/cpc-protos" }

# Media processing
ffmpeg-wasm = "0.1"

# Web framework
axum = "0.7"