[package]
name = "shtairir_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
shtairir = { path = "../../shared_packages/shtairir" }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"