[package]
name = "social_enhancements"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
rust_decimal = { workspace = true }
async-trait = { workspace = true }
common_utils = { path = "../common_utils" }
social_integration = { path = "../social_integration" }
volunteer_core = { path = "../volunteer_core" }
skill_exchange_core = { path = "../skill_exchange_core" }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

[features]
default = ["common-utils-integration"]
common-utils-integration = []