[package]
name = "consent_manager"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "consent_manager_example"
path = "src/main.rs"

[dependencies]
# Core dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }

# Database dependencies
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
sled = { workspace = true }

# Web framework dependencies
axum = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tower = "0.5"

# Bevy ECS dependencies (optional)
bevy_ecs = { version = "0.16", optional = true }
bevy_app = { version = "0.16", optional = true }

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["async_tokio"] }
rand = { workspace = true }

[[bench]]
name = "consent_manager_benchmark"
harness = false

[features]
default = []
bevy-integration = ["bevy_ecs", "bevy_app"]