name = "music-player"
description = "Complete music streaming with timestamped comments, visualizer, and social features"
version = "0.1.0"
dependencies = ["cpc-core", "p2panda"]
interface_version = "2.0"