[package]
name = "cpc_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
argon2 = "0.5"
uuid = { version = "1.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
redis = "0.23.0"