[package]
name = "messenger_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }

# Async support
async-trait = { workspace = true }

# Storage abstraction
storage_abstraction = { path = "../../core/storage_abstraction" }

# Event bus for real-time communication
event_bus = { path = "../../core/event_bus" }