[package]
name = "redis_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
redis = { version = "0.32.4", features = ["tokio-comp", "connection-manager"] }
bb8 = "0.9.0"
bb8-redis = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tokio-test = "0.4"