[package]
name = "redis_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }
bb8 = { workspace = true }
bb8-redis = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rmp-serde = "1.1"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "cache_example"
path = "examples/cache_example.rs"