[package]
name = "realtime_signaling"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# WebSocket dependencies
warp = "0.3"
tokio-tungstenite = { workspace = true }
url = "2.0"
futures = "0.3"
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }

# Event system
event_bus = { path = "../event_bus" }

# Collaboration engine for presence
collaboration_engine = { path = "../collaboration_engine" }

# Time handling
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"