[package]
name = "realtime_signaling"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tracing = "0.1"

# WebSocket dependencies
warp = "0.3"
tokio-tungstenite = "0.20"
url = "2.0"
futures = "0.3"
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Event system
event_bus = { path = "../event_bus" }

# Collaboration engine for presence
collaboration_engine = { path = "../collaboration_engine" }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"