[package]
name = "cpc-sheets"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }


# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Spreadsheet processing
calamine = "0.24"

# Caching
sled = { workspace = true }
redis = { workspace = true }
sha2 = "0.10"
redis_utils = { path = "../../shared_packages/redis_utils" }

# For testing
tokio = { workspace = true, features = ["full"] }