[package]
name = "cpc-sheets"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# CPC core modules
cpc-core-storage-abstraction = { path = "../../packages/core/storage_abstraction" }
cpc-core-event-bus = { path = "../../packages/core/event_bus" }
cpc-core-bi-visualization = { path = "../../packages/core/bi_visualization" }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Spreadsheet processing
calamine = "0.24"

# Caching
sled = { workspace = true }
redis = { workspace = true }
sha2 = "0.10"
redis_utils = { path = "../../shared_packages/redis_utils" }

# For testing
tokio = { workspace = true, features = ["full"] }