[package]
name = "cpc-social-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
cpc-core = { path = "../core" }
cpc-oauth2 = { path = "../core/oauth2" }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
serde_json = { workspace = true }
async-graphql = { workspace = true }

# Caching and storage
sled = { workspace = true }
bincode = "1.3"

# Finance dependencies
cpc_wallet = { path = "../core/wallet" }
rust_decimal = { workspace = true }

# App dependencies
allat = { path = "../../apps/allat" }
yapper = { path = "../../apps/yapper" }

[dev-dependencies]
rust_decimal_macros = { workspace = true }