[package]
name = "cpc-social-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
cpc-core = { path = "../core" }
cpc-oauth2 = { path = "../core/oauth2" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
serde_json = "1.0"
async-graphql = "7.0"

# Caching and storage
sled = "0.34"
bincode = "1.3"

# Finance dependencies
cpc_wallet = { path = "../core/wallet" }
rust_decimal = "1.26"

# App dependencies
allat = { path = "../../apps/allat" }
yapper = { path = "../../apps/yapper" }

[dev-dependencies]
rust_decimal_macros = "1.26"