[package]
name = "data_lakehouse"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
async-graphql = { workspace = true }


# For data processing
polars = { workspace = true }
# For the health module integration
cpc_health = { path = "../../apps/health" }

# For financial data processing
cpc_financial_core = { path = "../cpc_financial_core" }

# WebAssembly support
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
