[package]
name = "cpc-core-data-lakehouse"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
async-graphql = { workspace = true }

# WebM/AV1 handling
ffmpeg-wasm = "0.13.1"

# For data processing
polars = "0.40.0"
# For the health module integration
health = { path = "../../apps/health" }

# For financial data processing
cpc-financial-core = { path = "../cpc-financial-core" }

# WebAssembly support
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
