[package]
name = "cpc-messenger-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21.0"
stylist = { version = "0.13.0", features = ["yew_integration"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"

# Messenger backend
cpc-messenger = { path = "../messenger" }