[package]
name = "cpc-messenger-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true }
stylist = { workspace = true, features = ["yew_integration"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }

# Messenger backend
cpc-messenger = { path = "../messenger" }