[package]
name = "cpc-platform-yew"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yewdux = "0.9"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlElement",
    "Element",
    "Window",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "ImageData",
    "MediaStream",
    "MediaStreamConstraints",
    "MediaTrackConstraints",
    "MediaDeviceInfo",
    "MediaDevices",
    "Navigator",
    "HtmlVideoElement",
    "IntersectionObserver",
    "IntersectionObserverEntry",
    "TouchEvent",
    "Touch",
    "TouchList",
    "EventTarget",
    "MouseEvent",
    "DragEvent"
]}
uuid = { version = "1.0", features = ["serde", "v4"] }
cpc-core = { path = "../../packages/cpc-core" }
plotters = { version = "0.3", default-features = false, features = ["plotters-svg"] }
plotters-canvas = "0.3"
chrono = { version = "0.4", features = ["serde"] }
quirc-wasm = "0.1"
tracing = "0.1"
tracing-wasm = "0.2"
graphql-client = "0.11"
reqwest = { version = "0.11", features = ["json"] }
yew-hooks = "0.4"
gloo-timers = "0.2"
yew-router = "0.18"
anyhow = "1.0"