[package]
name = "cpc-studio"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.0", features = ["api-all"] }
bevy = { version = "0.10", features = ["dynamic", "render", "bevy_winit"] }
cpc-core = { path = "../../cpc-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
crossbeam-channel = "0.5"
wgpu = "0.15"
wry = "0.24"
# Permissive image processing library
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
bevy_gltf = { version = "0.10", features = [] }
bevy_wgpu = "0.10"
bevy_render = "0.10"
bevy_core_pipeline = "0.10"
bevy_pbr = "0.10"
bevy_asset = "0.10"
bevy_scene = "0.10"
bevy_transform = "0.10"
bevy_hierarchy = "0.10"
bevy_math = "0.10"
bevy_tasks = "0.10"
bevy_ecs = "0.10"
bevy_app = "0.10"
bevy_log = "0.10"
bevy_time = "0.10"
bevy_window = { version = "0.10", features = ["serialize"] }
bevy_utils = "0.10"
bevy_reflect = "0.10"
bevy_core = "0.10"
pollster = "0.3"