[package]
name = "shtairir_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
shtairir = { path = "../../shared_packages/shtairir" }
shtairir_registry = { path = "../../shared_packages/shtairir_registry" }
shtairir_execution = { path = "../../shared_packages/shtairir_execution" }
shtairir_editor = { path = "../../shared_packages/shtairir_editor" }

# UI framework
yew = { workspace = true }
yew-router = { workspace = true }
stylist = { workspace = true }

# WebAssembly support
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
gloo-timers = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }

# Utilities
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
wasm-logger = { workspace = true }

# Async support
futures-util = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"