[package]
name = "bi_visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Visualization library
plotters = { workspace = true }

# Image processing
image = "0.24"

# Bevy for interactive components
bevy = { workspace = true }

# Storage abstraction (for data retrieval)
storage_abstraction = { path = "../storage_abstraction" }

# Optional dependencies
async-trait = { workspace = true }

# PDF generation
pdf = { version = "0.7", optional = true }

# Time handling
chrono = { workspace = true, features = ["serde"] }

[features]
pdf_export = ["pdf"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
storage_abstraction = { path = "../storage_abstraction", features = ["in_memory"] }

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "finance_integration"
path = "examples/finance_integration.rs"

[[example]]
name = "health_integration"
path = "examples/health_integration.rs"