[package]
name = "storage_abstraction"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Storage backends
sled = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "sqlite"] }

# Optional dependencies
async-trait = { workspace = true }

# Decimal support
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

# UUID support
uuid = { workspace = true, features = ["v4", "serde"] }

# Time handling
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "health_integration"
path = "examples/health_integration.rs"

[[example]]
name = "finance_integration"
path = "examples/finance_integration.rs"