[package]
name = "task_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8", features = ["v4"] }
chrono = "0.4.38"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }