[package]
name = "visualization_context"
version = "0.1.0"
edition = "2021"
description = "Shared visualization context for cross-app communication"
authors = ["CPC Development Team"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
http = "0.2"
thiserror = { workspace = true }