[package]
name = "db_abstraction"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
diesel = { workspace = true, features = ["postgres", "sqlite", "r2d2", "chrono", "uuid"] }
diesel_migrations = "2.2.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
db_pool = { path = "../db_pool" }

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "schema_example"
path = "examples/schema_example.rs"