[package]
name = "cpc-api-gateway"
version = "0.1.0"
edition = "2021"
authors = ["CPC Cooperative <coop@cpc.dev>"]
description = "Central API Gateway for CPC platform"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "api-gateway"
path = "src/main.rs"

[dependencies]
# Core dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# CPC modules
cpc-api-integration = { path = "../api_integration" }
visualization_context = { path = "../../packages/visualization_context" }

# HTTP client for forwarding requests
reqwest = { version = "0.11", features = ["json"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# UUID support
uuid = { workspace = true, features = ["v4", "serde"] }

# Testing
tower = { version = "0.4", features = ["util"] }
http-body-util = "0.1"