[package]
name = "task_manager_core"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }