[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cpc-lib = { path = "../lib" }
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
tonic = "0.9"
prost = "0.11"
jsonwebtoken = "8.3"
argon2 = "0.5"
async-graphql = "4.0"
async-graphql-axum = "4.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "uuid", "chrono"] }