[package]
name = "web_app_template"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true }
yew-router = { workspace = true }
web_core = { path = "../../shared_packages/web_core" }
wasm-bindgen = { workspace = true }
wasm-logger = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]