[package]
name = "web_app_template"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21.0"
yew-router = "0.18.0"
web_core = { path = "../../shared_packages/web_core" }
wasm-bindgen = "0.2"
wasm-logger = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]