[package]
name = "learning_platform"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
yew = "0.21.0"
yew-router = "0.18.0"
stylist = { version = "0.13.0", features = ["yew_integration"] }
tauri = { version = "2.0", features = [] }
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
plotters = "0.3.5"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"
wasm-logger = "0.2"

[build-dependencies]
tonic-build = "0.11"

[lib]
crate-type = ["cdylib", "rlib"]