[package]
name = "learning_platform"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
yew = { workspace = true }
yew-router = { workspace = true }
stylist = { workspace = true, features = ["yew_integration"] }
tauri = { workspace = true, features = [] }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
plotters = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-logger = { workspace = true }
skill_development = { path = "../../shared_packages/skill_development" }
ml_core = { path = "../../shared_packages/ml_core" }
impact_viz = { path = "../../shared_packages/impact_viz" }
learning_impact_tracker = { path = "../../shared_packages/learning_impact_tracker" }
consent_manager = { path = "../../shared_packages/consent_manager" }
feedback_core = { path = "../../shared_packages/feedback_core" }

[build-dependencies]
tonic-build = "0.11"

[lib]
crate-type = ["cdylib", "rlib"]