[package]
name = "personal-finance"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0"
async-graphql-actix-web = "4.0"
actix-web = "4.0"
cpc-core = { path = "../../packages/cpc-core", features = ["finance"] }
rust-decimal = "1.29"
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
tracing = "0.1"
base64 = "0.21"
regex = "1.0"

[dev-dependencies]
tokio-test = "0.4"