[package]
name = "volunteer_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = "1.26"
rust_decimal_macros = "1.26"
async-trait = "0.1"
tokio = { version = "1.0", features = ["sync"] }
common_utils = { path = "../common_utils" }
wallet = { path = "../wallet" }
notification_core = { path = "../notification_core" }
cpay_core = { path = "../cpay_core" }
social_integration = { path = "../social_integration" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "decimal"] }

[features]
default = ["common-utils-integration"]
common-utils-integration = []