[package]
name = "cpc-crm"
version = "0.1.0"
edition = "2021"
authors = ["CPC Cooperative <coop@cpc.dev>"]
description = "Customer Relationship Management module for CPC platform"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
async-trait = "0.1"

# CPC core dependencies
cpc-core = { path = "../.." }

# Database dependencies
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# P2P dependencies
p2panda = { git = "https://github.com/p2panda/p2panda", rev = "v0.8.1" }

# Web dependencies
axum = { version = "0.7", optional = true }
async-graphql = { version = "7.0", optional = true }

# Bevy dependencies
bevy = { version = "0.14", optional = true }

# Yew dependencies
yew = { version = "0.21", optional = true }

# Test dependencies
wasm-bindgen-test = { version = "0.3", optional = true }
gloo-utils = { version = "0.2", optional = true }

[features]
default = []
web = ["axum", "async-graphql"]
bevy-ui = ["bevy"]
yew-ui = ["yew"]
test-yew = ["yew-ui", "wasm-bindgen-test", "gloo-utils"]

[lib]
crate-type = ["rlib"]