[package]
name = "shtairir_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
shtairir = { path = "../shtairir" }
yew = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"