[package]
name = "shtairir_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
shtairir = { path = "../shtairir" }
yew = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
yew = { version = "0.20", features = ["ssr"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }