[package]
name = "media"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
task_manager_core = { path = "../task_manager" }
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"