[package]
name = "pds"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core Technologies
axum = { workspace = true }
tracing = { workspace = true }

# GraphQL for Public API
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }

# Local packages
cpc-core = { path = "../../packages/cpc-core" }

# Common dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }