[package]
name = "pds"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
cpc-core = { path = "../../../packages/cpc-core" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
anyhow = "1.0"