[package]
name = "video_editor"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "video_editor_core"
path = "src/lib.rs"

[[bin]]
name = "video_editor"
path = "src/main.rs"

# Desktop runner crate will live at apps/video_editor_desktop (separate package added to workspace)

[features]
# wasm bindings and web/tauri specifics are behind features to keep core testable
wasm = []
tauri = []
# enable sqlx offline to avoid needing a live DB at build time
sqlx-offline = ["sqlx/offline"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4", "serde"] }

# Rendering / Engine
# Keep Bevy available for engine work; core stays headless. Desktop runner hosts preview.
bevy = { version = "0.16", default-features = false, features = ["bevy_winit", "x11", "serialize"] }
# GPU backend for effect processing
wgpu = "0.19"

# UI
yew = { version = "0.21.0", optional = true }
stylist = { version = "0.13", features = ["yew"], optional = true }

# Audio
rodio = { version = "0.21" }

# Storage / DB
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }

# Crypto (RustCrypto)
aes-gcm = "0.10"
sha2 = "0.10"
rand = "0.8"

# Caching / LRU
lru = "0.12"

# Spatial indexing for timeline clips
rstar = "0.12"

# Concurrency
rayon = "1.10"

# For memory-mapped files (large media handling)
memmap2 = "0.9"

# For plugin dynamic loading on desktop (placeholder, actual plugin API will be trait-based)
libloading = { version = "0.8", optional = true }

# GraphQL/gRPC placeholders for future integration (not used yet)
# async-graphql = "7"
# tonic = "0.12"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
pretty_assertions = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
# For stress and fuzz testing
arbitrary = { version = "1.3", features = ["derive"], optional = true }
libfuzzer-sys = { version = "0.4", optional = true }

[[bench]]
name = "timeline_bench"
harness = false

[[test]]
name = "stress_test"
path = "tests/stress_test.rs"

[[test]]
name = "fuzz_test"
path = "tests/fuzz_test.rs"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"