[package]
name = "collaborative_docs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# CRDT implementation
automerge-rs = "0.1"

# Database dependencies
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
sled = { workspace = true }

# Time handling
chrono = { workspace = true, features = ["serde"] }

# Consent service (assuming it's available in the workspace)
social_graph = { path = "../social_graph" }

# Additional dependencies for examples and testing
tempfile = "3.0"

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.5"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "provider_registration"
path = "examples/provider_registration.rs"

[[example]]
name = "app_initialization"
path = "examples/app_initialization.rs"

[[bench]]
name = "performance_bench"
harness = false