[package]
name = "collaborative_docs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
tracing = "0.1"

# CRDT implementation
automerge-rs = "0.1"

# Database dependencies
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
sled = "0.34"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Consent service (assuming it's available in the workspace)
social_graph = { path = "../social_graph" }

# Additional dependencies for examples and testing
tempfile = "3.0"

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.5"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "provider_registration"
path = "examples/provider_registration.rs"

[[example]]
name = "app_initialization"
path = "examples/app_initialization.rs"

[[bench]]
name = "performance_bench"
harness = false