[package]
name = "shtairir_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
shtairir = { path = "../shtairir" }
shtairir_registry = { path = "../shtairir_registry" }
yew = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
toml = { workspace = true }