[package]
name = "messenger_web"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
yew = { workspace = true }
yew-router = { workspace = true }
stylist = { workspace = true, features = ["yew_integration"] }
tauri = { workspace = true, features = [] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-logger = { workspace = true }
gloo-net = "0.5"
gloo-console = "0.3"
gloo-timers = { workspace = true }

# CPC Web Core shared package
web_core = { path = "../../shared_packages/web_core" }

# Messenger backend with UI components
cpc-messenger = { path = "../messenger_win64", features = ["web"] }

[build-dependencies]

[lib]
crate-type = ["cdylib", "rlib"]