[package]
name = "cpc_consent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
axum = "0.6"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"