[package]
name = "financial_impact_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

# Finance dependencies
env_logger = { workspace = true }

# Local dependencies
cpay_core = { path = "../cpay_core" }
cpc-financial-core = { path = "../cpc-financial-core" }