[package]
name = "cpc_oauth2"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async traits
async-trait = { workspace = true }

# OAuth2 implementation
oauth2 = { workspace = true, features = ["basic", "reqwest"] }

# Async runtime
tokio = { workspace = true, features = ["full"] }

# HTTP client for OAuth2 requests
reqwest = { workspace = true, features = ["json"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Encryption - using RustCrypto
aes-gcm = { workspace = true, features = ["aes"] }
rand = { workspace = true }
base64 = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# UUID for identifiers
uuid = { workspace = true, features = ["v4", "serde"] }

# Time handling
chrono = { workspace = true, features = ["serde"] }

# URL handling
url = { workspace = true }

# Consent manager integration
consent_manager = { path = "../consent_manager" }

# Audit framework integration
audit_framework = { path = "../audit_framework" }

# gRPC
prost = { workspace = true }
tonic = { workspace = true }

# Axum for REST API
axum = { workspace = true }

# Optional storage features
sled = { workspace = true, optional = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }

[build-dependencies]
tonic-build = "0.10.2"

[features]
default = ["sled_storage"]
sled_storage = ["sled"]
postgres_storage = ["sqlx"]
facebook = []
google = []
tiktok = []
twitter = []

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "oauth2_benchmark"
harness = false