[package]
name = "shtairir"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
shtairir_core = { path = "../shtairir_core" }
shtairir_registry = { path = "../shtairir_registry" }
shtairir_execution = { path = "../shtairir_execution" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "parser_benchmark"
harness = false

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"