[package]
name = "shtairir"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "parser_benchmark"
harness = false