[package]
name = "yapper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.8.0"
async-trait = "0.1.77"
argon2 = "0.2.36"
axum = "0.8.4"
consent_manager = { path = "../../packages/core/consent_manager" }
cpc_auth = { path = "../../packages/cpc_auth" }
cpc_rbac = { path = "../../packages/cpc_rbac" }
cpc_karma = { path = "../../packages/cpc_karma" }
cpc_consent = { path = "../../packages/cpc_consent" }
cpc_wallet = { path = "../../packages/core/wallet" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sled = "0.34"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = "1.26"
thiserror = "1.0"
social_integration = { path = "../../packages/social_integration" }
jsonwebtoken = "0.16.0"
tonic = "0.9"
prost = "0.12"
redis = "0.23"