[package]
name = "yapper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.8.0"
async-trait = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
consent_manager = { path = "../../packages/core/consent_manager" }
cpc_auth = { path = "../../packages/cpc_auth" }
cpc_rbac = { path = "../../packages/cpc_rbac" }
cpc_karma = { path = "../../packages/cpc_karma" }
cpc_consent = { path = "../../packages/cpc_consent" }
cpc_wallet = { path = "../../packages/core/wallet" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sled = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
social_integration = { path = "../../packages/social_integration" }
jsonwebtoken = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
redis = { workspace = true }