[package]
name = "bi_analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }

# Data processing
polars = { workspace = true }
ndarray = { workspace = true }
ndarray-stats = { workspace = true }

# Statistics core
cpc-statistics-core = { path = "../cpc-statistics-core" }

# Data structures
common_utils = { path = "../common_utils" }

# Consent management
consent_manager = { path = "../consent_manager" }

# Financial precision
cpc-financial-core = { path = "../cpc-financial-core" }

# Domain dependencies
cause_management = { path = "../cause_management" }
skill_development = { path = "../skill_development" }
volunteer_coordination = { path = "../volunteer_coordination" }
cpay_core = { path = "../cpay_core" }
feedback_analysis = { path = "../feedback_analysis" }

# Data lakehouse integration
data_lakehouse = { path = "../data_lakehouse" }

# Visualization integration
bi_visualization = { path = "../bi_visualization" }

# WebAssembly support
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
gloo-timers = { workspace = true, features = ["futures"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }