[package]
name = "feedback_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
feedback_core = { path = "../feedback_core" }
reviews = { path = "../reviews" }
survey = { path = "../survey" }
plotters = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }