[package]
name = "consent_manager"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "consent_manager_example"
path = "src/main.rs"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

# Database dependencies
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
sled = "0.34"

# Web framework dependencies
axum = "0.8"
tonic = "0.12"
prost = "0.13"
tower = "0.5"

# Tracing
tracing = "0.1"

[dev-dependencies]
tokio-test = "0.4"