[package]
name = "vulkan_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
rendering_core = { path = "../rendering_core" }
wry = { workspace = true }
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"

[dev-dependencies]
tempfile = "3.0"