[package]
name = "cpc-finance"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
cpc-core = { path = "../", features = ["finance"] }
cpc-net = { path = "../../cpc-net" }
async-graphql = "4.0"
async-graphql-actix-web = "4.0"
actix-web = "4.0"
rust-decimal = "1.29"
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
tracing = "0.1"
base64 = "0.21"
regex = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "rust_decimal"] }

# p2p dependencies
p2panda = { version = "0.1", optional = true }
libp2p = { version = "0.53", features = ["tcp", "dns", "websocket", "noise", "yamux", "ping", "macros"] }

# Visualization dependencies
bevy = { version = "0.13", optional = true }
plotters = { version = "0.3", optional = true }
yew = { version = "0.21", optional = true }

[features]
default = []
ocr = ["cpc-core/ocr"]
p2p = ["p2panda"]
visualization = ["bevy", "plotters"]
web = ["yew"]