[package]
name = "web_core"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true }
yew-router = { workspace = true }
stylist = { workspace = true, features = ["yew_integration"] }
gloo-net = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
md5 = "0.7"
uuid = { workspace = true, features = ["v4", "serde"] }
tonic = { workspace = true, features = ["codegen", "transport"] }
prost = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"