[package]
name = "messenger_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tonic = { workspace = true, optional = true }
prost = { workspace = true, optional = true }

# Async support
async-trait = { workspace = true }
async-graphql = { workspace = true, optional = true }
async-stream = { workspace = true, optional = true }
futures-util = { workspace = true, optional = true }
tokio = { workspace = true, features = ["time"], optional = true }

# Storage abstraction
storage_abstraction = { path = "../../core/storage_abstraction" }

# Event bus for real-time communication
event_bus = { path = "../../core/event_bus" }

[features]
default = []
graphql = ["async-graphql", "async-stream", "futures-util", "tokio"]
auth = ["tonic", "prost"]