[package]
name = "learning_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
prost-types = "0.13"

[build-dependencies]
tonic-build = "0.12"

[[bin]]
name = "migrate"
path = "bin/migrate.rs"

[[bin]]
name = "grpc_server"
path = "src/bin/grpc_server.rs"