[package]
name = "learning_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
tonic-build = "0.12"

[[bin]]
name = "migrate"
path = "bin/migrate.rs"

[[bin]]
name = "grpc_server"
path = "src/bin/grpc_server.rs"