[package]
name = "task_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }

# GraphQL
async-graphql = { workspace = true }
async-graphql-actix-web = "7.0"

# P2P sync
# Note: Update path based on current shared_packages structure
# cpc-net = { path = "../../shared_packages/network" }

# Web framework
actix-web = "4.0"
tokio = { workspace = true, features = ["full"] }

# Validation
validator = { version = "0.16", features = ["derive"] }

# Notifications
notify-rust = { version = "4.0", optional = true }

[dev-dependencies]
tokio-test = "0.4"