[package]
name = "cpc-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
thiserror = { workspace = true }

# CPC domain dependencies
# finance_domain = { path = "../finance_domain" }

# For testing
tempfile = "3.0"