[package]
name = "db_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7"
rusqlite = { version = "0.30", features = ["bundled"] }
bb8 = "0.9.0"
bb8-rusqlite = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "postgres_example"
path = "examples/postgres_example.rs"
