[package]
name = "db_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true }
rusqlite = { version = "0.30", features = ["bundled"] }
bb8 = { workspace = true }
bb8-rusqlite = { version = "0.1.0" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "postgres_example"
path = "examples/postgres_example.rs"
