[package]
name = "shtairir_blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
shtairir_core = { path = "../shtairir_core" }
shtairir_registry = { path = "../shtairir_registry" }
shtairir = { path = "../shtairir" }
anyhow = { workspace = true }
thiserror = { workspace = true }
libm = { workspace = true }
nalgebra = { workspace = true }
statrs = { workspace = true }
fixed = { workspace = true }
glam = { workspace = true }
argmin = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }