[package]
name = "cpc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core Technologies
bevy = { workspace = true }
p2panda-core = { workspace = true }
p2panda-net = { workspace = true }
p2panda-store = { workspace = true }
plotters = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
rodio = { workspace = true }
pdf = { workspace = true }

# GraphQL for Public API
async-graphql = { workspace = true, features = ["chrono", "uuid"] }

# Common dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

# Financial operations
rust_decimal = { version = "1.34", features = ["serde", "std"] }
rust_decimal_macros = "1.34"

# Cryptography
ed25519-dalek = { version = "2.1", features = ["serde"] }
rand = "0.8"
hex = "0.4"

# HTTP client for OAuth
reqwest = { version = "0.11", features = ["json"] }

# Android support (optional)
jni = { version = "0.21", optional = true }
winit = { version = "0.29", features = ["android-native-activity"], optional = true }

[features]
default = []
android = ["jni", "winit"]