[package]
name = "social_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
async-graphql = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
tonic = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["postgres", "uuid", "chrono", "runtime-tokio-rustls"] }
postgres-types = { version = "0.2", features = ["derive"] }
lru = "0.12"
thiserror = { workspace = true }
semver = "1.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Shared packages
consent_manager = { path = "../consent_manager" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
criterion = "0.5"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "full_example"
path = "examples/full_example.rs"

[[example]]
name = "content_provider_example"
path = "examples/content_provider_example.rs"

[[example]]
name = "state_migration_example"
path = "examples/state_migration_example.rs"

[[example]]
name = "dynamic_provider_example"
path = "examples/dynamic_provider_example.rs"

[[example]]
name = "hot_swap_example"
path = "examples/hot_swap_example.rs"

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"

[[test]]
name = "repository_integration_test"
path = "tests/repository_integration_test.rs"

[[test]]
name = "content_provider_test"
path = "tests/content_provider_test.rs"

[[test]]
name = "content_fetching_test"
path = "tests/content_fetching_test.rs"

[[test]]
name = "integration_content_provider_test"
path = "tests/integration_content_provider_test.rs"

[[test]]
name = "consent_service_test"
path = "tests/consent_service_test.rs"

[[test]]
name = "social_service_integration_test"
path = "tests/social_service_integration_test.rs"

[[test]]
name = "integration_consent_test"
path = "tests/integration_consent_test.rs"

[[test]]
name = "state_migration_test"
path = "tests/state_migration_test.rs"

[[bench]]
name = "repository_benchmark"
harness = false

[[test]]
name = "error_handling_test"
path = "tests/error_handling_test.rs"