[package]
name = "volunteer_coordination"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v4"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
parking_lot = "0.12"

# Internal crates in the workspace may rely on these traits and types
# Adjust as needed when integrating with the full workspace Cargo.