[package]
name = "volunteer_coordination"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
parking_lot = "0.12"

# Internal crates in the workspace may rely on these traits and types
# Adjust as needed when integrating with the full workspace Cargo.