[package]
name = "cpc-ci-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7"
clap = { version = "4", features = ["derive"] }
similar = "2.6"
anyhow = "1.0"
thiserror = "1.0"
walkdir = "2.5"

# Depend on the API server crate to access its deterministic schema builder
api_server = { path = "../../apps/api_server" }