[package]
name = "skill_development"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
clap = { version = "4.4", features = ["derive"] }
dotenvy = "0.15"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
rand = { workspace = true }
tonic = { workspace = true, features = ["prost", "codegen"] }
prost = { workspace = true }
async-trait = { workspace = true }
sled = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Optimization core
optimization_core = { path = "../optimization_core" }
ndarray = { workspace = true }
ml_core = { path = "../ml_core" }

[build-dependencies]
tonic-build = "0.12"

[[bin]]
name = "migrate"
path = "bin/migrate.rs"

[[bin]]
name = "grpc_server"
path = "src/bin/grpc_server.rs"