[package]
name = "volunteer-coordination-admin"
version = "0.1.0"
edition = "2021"
authors = ["CPC Cooperative <coop@cpc.dev>"]
description = "Admin dashboard for volunteer coordination impact analytics"

[dependencies]
# Core dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true, features = ["serde"] }

# Web framework
yew = { workspace = true, features = ["csr"] }
yew-router = { workspace = true }
stylist = { workspace = true, features = ["yew_integration"] }

# CPC modules
volunteer_impact_tracker = { path = "../../shared_packages/volunteer_impact_tracker" }
volunteer_coordination = { path = "../../shared_packages/volunteer_coordination" }
learning_impact_tracker = { path = "../../shared_packages/learning_impact_tracker" }
skill_development = { path = "../../shared_packages/skill_development" }
impact_viz = { path = "../../shared_packages/impact_viz", features = ["web_components"] }
consent_manager = { path = "../../shared_packages/consent_manager" }
cause_management = { path = "../../shared_packages/cause_management" }

# Logging
wasm-logger = { workspace = true }

# Build
trunk = "0.17"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = []