[package]
name = "common_utils"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
rust-crypto = "0.2"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["sync", "time", "macros"] }
futures = "0.3"
rand = "0.8"

[dev-dependencies]
tracing-test = "0.2"
tokio = { version = "1.0", features = ["sync", "time", "macros", "rt", "rt-multi-thread"] }