[package]
name = "common_utils"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rmp-serde = "1.1"
rust-crypto = "0.2"
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["sync", "time", "macros"] }
futures = "0.3"
rand = { workspace = true }

[dev-dependencies]
tracing-test = "0.2"
tokio = { workspace = true, features = ["sync", "time", "macros", "rt", "rt-multi-thread"] }