[package]
name = "pds-tauri"
version = "0.1.0"
description = "CPC Desktop Client"
authors = ["CPC Team"]
license = "MIT"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["api-all", "system-tray", "updater"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "fs", "net"] }
cpc-core = { path = "../../../packages/cpc-core" }
cpc-net = { path = "../../../packages/cpc-net" }
image = "0.24"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bevy = { version = "0.12", features = ["dynamic_linking"] }
ort = "2.0"
ndarray = "0.15"
ring = "0.17"
zeroize = "1.6"
base64 = "0.21"
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.4", features = ["cors", "fs"] }
async-graphql = "7.0"
async-graphql-axum = "7.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[[bin]]
name = "pds-tauri"
path = "src/main.rs"

[lib]
name = "cpc_pds_lib"
path = "src/lib.rs"