[package]
name = "cpc-net"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Core Technologies
p2panda-core = { workspace = true }
p2panda-net = { workspace = true }
p2panda-store = { workspace = true }
tracing = { workspace = true }

# gRPC for Internal API
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

# Common dependencies
tokio = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
pdf = "0.9.0"
[build-dependencies]
tonic-build = "0.11"
