[package]
name = "cpc-net"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p2panda = "0.8"
anyhow = "1.0"
async-trait = "0.1"
libp2p-core = { version = "0.41.0", features = ["noise"] }
libp2p-kad = { version = "0.43.0", features = ["metrics"] }
libp2p-bitswap = { version = "0.44.0" }
libp2p-gossipsub = "0.47.0"
libp2p-metrics = "0.16.0"
libp2p-tcp = "0.42.0"
libp2p-websocket = "0.45.0"
libp2p-quic = "0.5.0"
libp2p-identify = "0.44.0"
libp2p-ping = "0.44.0"
libp2p-yamux = "0.44.0"
libp2p-noise = "0.44.0"
blake3 = "1.5.0"
secp256k1 = "0.27.0"
x25519-dalek = "2.0.0"
lru = "0.12"
metrics = "0.21.0"
rand = "0.8.5"
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync"] }
prost-types = "0.12"
bytes = "1.5"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
tempfile = "3.8"

[build-dependencies]
tonic-build = "0.10"