[package]
name = "opengl_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
rendering_core = { path = "../rendering_core" }
wry = { workspace = true }
glow = { workspace = true }

[dev-dependencies]
tempfile = "3.0"