[package]
name = "cpc-messenger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "messenger"
path = "src/main.rs"

[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Domain layer
messenger_domain = { path = "../../shared_packages/messenger", features = ["graphql", "auth"] }

# Application layer
messenger_app = { path = "../../shared_packages/messenger_app" }

# Infrastructure layer
messenger_infrastructure = { path = "../../shared_packages/messenger_infrastructure" }

# Shared packages
social_interactions = { path = "../../packages/core/social_interactions" }
media = { path = "../../packages/core/media" }

# Web dependencies (for UI components)
yew = { workspace = true, optional = true }
stylist = { workspace = true, features = ["yew_integration"], optional = true }
gloo-net = { version = "0.5", optional = true }
gloo-console = { version = "0.3", optional = true }
gloo-timers = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }

# Web framework
axum = { workspace = true }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# GraphQL
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }

# WebSocket support
tokio-tungstenite = { workspace = true }
async-tungstenite = "0.20"

# OAuth2 for authentication
oauth2 = { workspace = true }

# Sled for local caching
sled = { workspace = true }

# Encryption
rust-crypto = "0.2"

# gRPC
tonic = { workspace = true }
prost = { workspace = true }

# Consent manager
consent_manager = { path = "../../packages/core/consent_manager" }

[dev-dependencies]
tempfile = "3.8"

[features]
web = ["yew", "stylist", "gloo-net", "gloo-console", "gloo-timers", "wasm-bindgen", "wasm-bindgen-futures", "web-sys", "js-sys"]