[package]
name = "social_interactions"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid", "chrono", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["full"] }

# Error handling
thiserror = { workspace = true }

# Utilities
std = "0.0"
futures = "0.3"

# Shared packages
notification_core = { path = "../notification_core" }

[dev-dependencies]
# Testing
mockall = "0.12"
tokio-test = "0.4"
test-case = "3.0"

[lib]
name = "social_interactions"
path = "src/lib.rs"

[[test]]
name = "reaction_service_tests"
path = "tests/reaction_service_tests.rs"

[[test]]
name = "comment_service_tests"
path = "tests/comment_service_tests.rs"

[[test]]
name = "share_service_tests"
path = "tests/share_service_tests.rs"

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"