[package]
name = "rendering_core"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
# For testing
tempfile = "3.0"