[package]
name = "cpc-live-streaming"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "live-streaming"
path = "src/main.rs"

[[bin]]
name = "live-streaming-tauri"
path = "src/main_tauri.rs"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
tracing = "0.1"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Async
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# GraphQL
async-graphql = "7.0"

# Web framework
axum = "0.7"

# WebRTC
wry = "0.52.1"

# Tauri
tauri = { version = "2.0", features = ["wry"] }
tauri-build = "2.0"

# Media processing
ffmpeg-wasm = "0.1"
plotters = "0.3"

# CPC dependencies
cpc-messenger = { path = "../messenger" }
cpc-social-integration = { path = "../../shared_packages/social_integration" }
cpc-notification-core = { path = "../../shared_packages/notification_core" }

# P2P networking
p2panda = "0.1"
iroh = "0.1"

# Audio processing
rodio = "0.17"

# WebSocket support
tokio-tungstenite = "0.20.1"

# Web frontend
yew = { version = "0.21.0", features = ["csr"] }
stylist = { version = "0.13.0", features = ["yew_integration"] }
wasm-bindgen = "0.2.100"
wasm-logger = "0.2.0"
web-sys = "0.3.77"