[package]
name = "cpc-live-streaming"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "live-streaming"
path = "src/main.rs"

[[bin]]
name = "live-streaming-tauri"
path = "src/main_tauri.rs"

[dependencies]
# Core dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tracing = { workspace = true }

# Database
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Async
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# GraphQL
async-graphql = { workspace = true }

# Web framework
axum = { workspace = true }

# WebRTC
wry = { workspace = true }

# Tauri
tauri = { workspace = true, features = ["wry"] }
tauri-build = "2.0"

# Media processing
ffmpeg-wasm = "0.1"
plotters = { workspace = true }

# CPC dependencies
cpc-messenger = { path = "../messenger" }
cpc-social-integration = { path = "../../shared_packages/social_integration" }
cpc-notification-core = { path = "../../shared_packages/notification_core" }

# P2P networking
p2panda = { workspace = true }
iroh = "0.1"

# Audio processing
rodio = { workspace = true }

# WebSocket support
tokio-tungstenite = { workspace = true }

# Web frontend
yew = { workspace = true, features = ["csr"] }
stylist = { workspace = true, features = ["yew_integration"] }
wasm-bindgen = { workspace = true }
wasm-logger = { workspace = true }
web-sys = { workspace = true }