name: CI
on: [push, pull_request]

jobs:
  video_editor_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Set WGPU_BACKEND
        run: echo "WGPU_BACKEND=dx12" >> $GITHUB_ENV
      - name: Run tests
        run: cargo test -p video_editor -- --test-threads=1