[package]
name = "shtairir_example"
version = "0.1.0"
edition = "2021"

[dependencies]
shtairir = { path = "../../shared_packages/shtairir" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }