[package]
name = "cpc-protos"
version = "0.1.0"
edition = "2021"

[dependencies]
# gRPC for Internal API
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

# Common dependencies
serde = { workspace = true }
chrono = { workspace = true }

[build-dependencies]
tonic-build = "0.11"