[package]
name = "cpc-core-data-lakehouse"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1"
async-graphql = "5.0"

# WebM/AV1 handling
ffmpeg-wasm = "0.13.1"

# For data processing
polars = "0.40.0"

# For the health module integration
cpc-core-health = { path = "../health" }